# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mango\PycharmProjects\FanTools\widget\TranslateMultiPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1144, 679)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(-1, 42, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SubtitleLabel = SubtitleLabel(Form)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.horizontalLayout.addWidget(self.SubtitleLabel)
        self.SplitPushButton = SplitPushButton(Form)
        self.SplitPushButton.setObjectName("SplitPushButton")
        self.horizontalLayout.addWidget(self.SplitPushButton)
        self.ToolButton_Guide = ToolButton(Form)
        self.ToolButton_Guide.setObjectName("ToolButton_Guide")
        self.horizontalLayout.addWidget(self.ToolButton_Guide)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SingleDirectionScrollArea = SingleDirectionScrollArea(Form)
        self.SingleDirectionScrollArea.setWidgetResizable(True)
        self.SingleDirectionScrollArea.setObjectName("SingleDirectionScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 919, 553))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SingleDirectionScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.SingleDirectionScrollArea)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.PushButton_SaveProject = PushButton(Form)
        self.PushButton_SaveProject.setObjectName("PushButton_SaveProject")
        self.verticalLayout.addWidget(self.PushButton_SaveProject)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PushButton_Glossary = PushButton(Form)
        self.PushButton_Glossary.setTabletTracking(False)
        self.PushButton_Glossary.setObjectName("PushButton_Glossary")
        self.horizontalLayout_4.addWidget(self.PushButton_Glossary)
        self.ToolButton_ReloadGlossary = ToolButton(Form)
        self.ToolButton_ReloadGlossary.setObjectName("ToolButton_ReloadGlossary")
        self.horizontalLayout_4.addWidget(self.ToolButton_ReloadGlossary)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.ComboBox_API = qfluentwidgets.ComboBox(Form)
        self.ComboBox_API.setObjectName("ComboBox_API")
        self.verticalLayout.addWidget(self.ComboBox_API)
        self.PrimaryPushButton_TranslateWithAPI = PrimaryPushButton(Form)
        self.PrimaryPushButton_TranslateWithAPI.setObjectName("PrimaryPushButton_TranslateWithAPI")
        self.verticalLayout.addWidget(self.PrimaryPushButton_TranslateWithAPI)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PushButton_PageBefore = PushButton(Form)
        self.PushButton_PageBefore.setObjectName("PushButton_PageBefore")
        self.horizontalLayout_3.addWidget(self.PushButton_PageBefore)
        self.PushButton_PageAfter = PushButton(Form)
        self.PushButton_PageAfter.setObjectName("PushButton_PageAfter")
        self.horizontalLayout_3.addWidget(self.PushButton_PageAfter)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.CaptionLabel = CaptionLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CaptionLabel.sizePolicy().hasHeightForWidth())
        self.CaptionLabel.setSizePolicy(sizePolicy)
        self.CaptionLabel.setMaximumSize(QtCore.QSize(190, 16777215))
        self.CaptionLabel.setWordWrap(True)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.verticalLayout.addWidget(self.CaptionLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.BodyLabel = BodyLabel(Form)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_2.addWidget(self.BodyLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SubtitleLabel.setText(_translate("Form", "Subtitle label"))
        self.SplitPushButton.setProperty("text_", _translate("Form", "下拉选择快速操作类型"))
        self.PushButton_SaveProject.setText(_translate("Form", "保存项目"))
        self.PushButton_Glossary.setText(_translate("Form", "术语表"))
        self.ComboBox_API.setText(_translate("Form", "选择API以供调用"))
        self.PrimaryPushButton_TranslateWithAPI.setText(_translate("Form", "批量调用API执行翻译"))
        self.PushButton_PageBefore.setText(_translate("Form", "<<<"))
        self.PushButton_PageAfter.setText(_translate("Form", ">>>"))
        self.CaptionLabel.setText(_translate("Form", "<html><head/><body><p>本页面是列表多项词条翻译器的页面，针对某一词条的工具按钮均放置在该词条卡片上，所有词条在发生变化之后都会自动保存，但您仍然需要手动⬆️保存项目⬆️。</p><p>您需要先在工具箱设置中配置翻译API的凭证，然后才能调用API进行翻译。您点击上方调用API翻译的按钮后，本页的所有未提供翻译文本的词条都会被提交翻译，翻译结果将自动填充至译文输入行中。</p><p>批量调用API翻译并不能让本页的所有内容瞬间完成翻译，API调用接口会屏蔽过快的访问，因此两次翻译之间存在一秒的间隔。</p></body></html>"))
        self.BodyLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">本翻译工具仅具备调用外部 API 进行翻译的能力；任何外部翻译 API 均与本工具无任何关系。本工具无法保证外部 API 调用所得翻译结果的准确性与可靠性。</span></p></body></html>"))
from qfluentwidgets import BodyLabel, CaptionLabel, PrimaryPushButton, PushButton, SingleDirectionScrollArea, SplitPushButton, SubtitleLabel, ToolButton
