name: Build and Publish Writerside Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Writerside
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: Writerside/hi
          artifact: webHelpHI2-all.zip
          docker_version: 241.18775

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: webHelpHI2-all.zip
